# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
    labels: ["requirements", "enhancement"]
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["ci/cd", "enhancement"]
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
